import { useState } from "react";
import axios from "axios";
import {
  Camera,
  Upload,
  AlertCircle,
  Loader,
  Leaf,
  TrendingUp,
  Activity,
  AlertTriangle,
  FileImage,
  Sparkles,
  CheckCircle2,
  Clock,
  Download,
  Share2,
  X,
} from "lucide-react";

const DiseaseDetection = () => {
  const [selectedFile, setSelectedFile] = useState(null);
  const [previewUrl, setPreviewUrl] = useState(null);
  const [detecting, setDetecting] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");

  const handleFileSelect = (e) => {
    const file = e.target.files[0];
    if (file) {
      if (!file.type.startsWith("image/")) {
        setError("Please select a valid image file");
        return;
      }

      if (file.size > 10 * 1024 * 1024) {
        setError("File size must be less than 10MB");
        return;
      }

      setSelectedFile(file);
      setPreviewUrl(URL.createObjectURL(file));
      setResult(null);
      setError("");
    }
  };

  const handleDetect = async () => {
    if (!selectedFile) {
      setError("Please select an image first");
      return;
    }

    setDetecting(true);
    setError("");

    const formData = new FormData();
    formData.append("file", selectedFile);

    try {
      const response = await axios.post(
        "http://localhost:8000/detect-disease",
        formData,
        {
          headers: { "Content-Type": "multipart/form-data" },
          timeout: 60000, // 60 second timeout
        }
      );

      setResult(response.data);
    } catch (err) {
      setError(
        err.response?.data?.detail ||
          "Detection failed. Please ensure Python server is running on port 8000."
      );
      console.error("Detection error:", err);
    } finally {
      setDetecting(false);
    }
  };

  const handleDownloadTreatment = () => {
    if (!result || !result.treatment_plan) return;

    const content = `
CROP DISEASE TREATMENT PLAN
Generated: ${new Date().toLocaleString()}
=====================================

Crop: ${result.crop_type}
Disease: ${result.disease_name}
Severity: ${result.severity.level}
Confidence: ${(result.confidence * 100).toFixed(1)}%
Growth Stage: ${result.growth_stage.stage}

=====================================
${result.treatment_plan}
=====================================

Generated by AI Crop Doctor
Powered by Groq LLM
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${result.crop_type}_${result.disease_name.replace(
      /\s+/g,
      "_"
    )}_Treatment.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleShareTreatment = async () => {
    if (!result || !result.treatment_plan) return;

    const shareText = `🌾 Crop Disease Treatment Plan\n\nCrop: ${result.crop_type}\nDisease: ${result.disease_name}\n\n${result.treatment_plan}`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: `Treatment for ${result.disease_name}`,
          text: shareText,
        });
      } catch (err) {
        console.log("Share cancelled or failed", err);
      }
    } else {
      // Fallback: Copy to clipboard
      navigator.clipboard.writeText(shareText).then(() => {
        alert("Treatment plan copied to clipboard!");
      });
    }
  };

  const getSeverityColor = (level) => {
    const colors = {
      None: "from-green-400 to-green-600",
      Low: "from-yellow-400 to-yellow-600",
      Moderate: "from-orange-400 to-orange-600",
      High: "from-red-400 to-red-600",
    };
    return colors[level] || "from-gray-400 to-gray-600";
  };

  const getSeverityBadge = (level) => {
    const styles = {
      None: "bg-green-100 text-green-700 border-green-300",
      Low: "bg-yellow-100 text-yellow-700 border-yellow-300",
      Moderate: "bg-orange-100 text-orange-700 border-orange-300",
      High: "bg-red-100 text-red-700 border-red-300",
    };
    return styles[level] || "bg-gray-100 text-gray-700 border-gray-300";
  };

  const clearAll = () => {
    setSelectedFile(null);
    setPreviewUrl(null);
    setResult(null);
    setError("");
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 via-blue-50 to-purple-50 p-6">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="bg-white rounded-2xl shadow-lg p-8 mb-6 border-t-4 border-green-500">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="bg-gradient-to-br from-green-400 to-green-600 p-4 rounded-xl shadow-lg">
                <Camera className="w-10 h-10 text-white" />
              </div>
              <div>
                <h1 className="text-4xl font-bold text-gray-800 flex items-center gap-2">
                  AI Crop Doctor
                  <Sparkles className="w-8 h-8 text-yellow-500" />
                </h1>
                <p className="text-gray-600 mt-1">
                  Instant disease detection & treatment powered by AI
                </p>
              </div>
            </div>
            {(result || previewUrl) && (
              <button
                onClick={clearAll}
                className="px-6 py-3 bg-gray-100 hover:bg-gray-200 text-gray-700 font-semibold rounded-xl transition-all flex items-center gap-2"
              >
                <X size={20} />
                Clear All
              </button>
            )}
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Upload Section */}
          <div className="bg-white rounded-2xl shadow-lg p-6">
            <h2 className="text-2xl font-bold text-gray-800 mb-4 flex items-center gap-2">
              <Upload className="w-6 h-6 text-blue-600" />
              Upload Crop Image
            </h2>

            <div className="mb-6">
              <label className="block w-full">
                <div className="border-3 border-dashed border-gray-300 rounded-2xl p-10 text-center hover:border-blue-500 hover:bg-blue-50 transition-all cursor-pointer">
                  {previewUrl ? (
                    <div className="space-y-4">
                      <img
                        src={previewUrl}
                        alt="Preview"
                        className="max-h-80 mx-auto rounded-xl shadow-xl border-4 border-white object-contain"
                      />
                      <p className="text-sm text-gray-600 font-medium truncate px-4">
                        {selectedFile.name}
                      </p>
                    </div>
                  ) : (
                    <div className="space-y-4">
                      <FileImage className="w-20 h-20 text-gray-400 mx-auto" />
                      <div>
                        <p className="text-xl text-gray-700 font-bold">
                          Click to upload image
                        </p>
                        <p className="text-sm text-gray-500 mt-2">
                          JPEG, PNG, or JPG • Max 10MB
                        </p>
                      </div>
                    </div>
                  )}
                </div>
                <input
                  type="file"
                  accept="image/*"
                  onChange={handleFileSelect}
                  className="hidden"
                />
              </label>
            </div>

            {/* Action Buttons */}
            <div className="flex gap-3">
              <button
                onClick={handleDetect}
                disabled={!selectedFile || detecting}
                className="flex-1 bg-gradient-to-r from-green-500 to-green-600 hover:from-green-600 hover:to-green-700 text-white font-bold py-4 rounded-xl transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-3 shadow-lg hover:shadow-xl transform hover:-translate-y-0.5"
              >
                {detecting ? (
                  <>
                    <Loader className="w-6 h-6 animate-spin" />
                    Analyzing with AI...
                  </>
                ) : (
                  <>
                    <Activity className="w-6 h-6" />
                    Detect Disease
                  </>
                )}
              </button>

              {previewUrl && (
                <button
                  onClick={clearAll}
                  className="px-8 py-4 border-2 border-gray-300 text-gray-700 font-semibold rounded-xl hover:bg-gray-50 transition-all"
                >
                  Clear
                </button>
              )}
            </div>

            {/* Instructions */}
            <div className="mt-6 bg-gradient-to-r from-blue-50 to-blue-100 border-l-4 border-blue-500 p-5 rounded-xl">
              <h4 className="font-bold text-blue-900 mb-3 flex items-center gap-2">
                <Camera size={20} />
                Tips for Best Results
              </h4>
              <ul className="text-sm text-blue-800 space-y-2">
                <li className="flex items-center gap-2">
                  <CheckCircle2
                    size={16}
                    className="text-blue-600 flex-shrink-0"
                  />
                  Capture clear, well-lit photos of affected leaves
                </li>
                <li className="flex items-center gap-2">
                  <CheckCircle2
                    size={16}
                    className="text-blue-600 flex-shrink-0"
                  />
                  Include the entire leaf in the frame
                </li>
                <li className="flex items-center gap-2">
                  <CheckCircle2
                    size={16}
                    className="text-blue-600 flex-shrink-0"
                  />
                  Avoid blurry or dark images
                </li>
                <li className="flex items-center gap-2">
                  <CheckCircle2
                    size={16}
                    className="text-blue-600 flex-shrink-0"
                  />
                  Take photos from multiple angles if unsure
                </li>
              </ul>
            </div>
          </div>

          {/* Results Section */}
          <div className="space-y-6">
            {/* Error Display */}
            {error && (
              <div className="bg-red-50 border-l-4 border-red-500 p-5 rounded-xl shadow-md animate-shake">
                <div className="flex items-start gap-3">
                  <AlertCircle className="w-6 h-6 text-red-500 flex-shrink-0 mt-0.5" />
                  <div className="flex-1">
                    <h3 className="font-bold text-red-800 mb-1">
                      Detection Error
                    </h3>
                    <p className="text-red-700 text-sm">{error}</p>
                  </div>
                  <button
                    onClick={() => setError("")}
                    className="text-red-400 hover:text-red-600"
                  >
                    <X size={20} />
                  </button>
                </div>
              </div>
            )}

            {/* Detection Results */}
            {result && result.success && (
              <>
                {/* Quick Summary Card */}
                {result.quick_summary && (
                  <div
                    className={`bg-gradient-to-r ${
                      result.disease_status === "healthy"
                        ? "from-green-500 to-green-600"
                        : "from-orange-500 to-red-600"
                    } rounded-2xl shadow-2xl p-6 text-white animate-fadeIn`}
                  >
                    <div className="flex items-center gap-3 mb-3">
                      <Sparkles className="w-8 h-8 animate-pulse" />
                      <h2 className="text-2xl font-bold">AI Analysis</h2>
                    </div>
                    <p className="text-xl font-medium leading-relaxed">
                      {result.quick_summary}
                    </p>
                  </div>
                )}

                {/* Detection Info Cards */}
                <div className="grid grid-cols-2 gap-4 animate-fadeIn">
                  <div className="bg-white rounded-xl shadow-lg p-5 border-l-4 border-green-500 hover:shadow-xl transition-shadow">
                    <div className="flex items-center gap-2 mb-2">
                      <Leaf className="w-5 h-5 text-green-600" />
                      <span className="text-sm text-gray-600 font-medium">
                        Crop Type
                      </span>
                    </div>
                    <p className="text-2xl font-bold text-gray-800">
                      {result.crop_type}
                    </p>
                  </div>

                  <div
                    className={`bg-white rounded-xl shadow-lg p-5 border-l-4 ${
                      result.disease_status === "healthy"
                        ? "border-green-500"
                        : "border-red-500"
                    } hover:shadow-xl transition-shadow`}
                  >
                    <div className="flex items-center gap-2 mb-2">
                      <Activity className="w-5 h-5 text-blue-600" />
                      <span className="text-sm text-gray-600 font-medium">
                        Disease
                      </span>
                    </div>
                    <p className="text-xl font-bold text-gray-800">
                      {result.disease_name}
                    </p>
                  </div>

                  <div className="bg-white rounded-xl shadow-lg p-5 border-l-4 border-purple-500 hover:shadow-xl transition-shadow">
                    <div className="flex items-center gap-2 mb-2">
                      <TrendingUp className="w-5 h-5 text-purple-600" />
                      <span className="text-sm text-gray-600 font-medium">
                        Confidence
                      </span>
                    </div>
                    <div className="flex items-center gap-3">
                      <p className="text-2xl font-bold text-gray-800">
                        {(result.confidence * 100).toFixed(1)}%
                      </p>
                      <div className="flex-1 bg-gray-200 rounded-full h-2">
                        <div
                          className="bg-purple-600 h-2 rounded-full transition-all duration-1000"
                          style={{ width: `${result.confidence * 100}%` }}
                        ></div>
                      </div>
                    </div>
                  </div>

                  <div className="bg-white rounded-xl shadow-lg p-5 border-l-4 border-orange-500 hover:shadow-xl transition-shadow">
                    <div className="flex items-center gap-2 mb-2">
                      <AlertTriangle className="w-5 h-5 text-orange-600" />
                      <span className="text-sm text-gray-600 font-medium">
                        Severity
                      </span>
                    </div>
                    <span
                      className={`inline-block px-4 py-2 rounded-lg text-sm font-bold border-2 ${getSeverityBadge(
                        result.severity.level
                      )}`}
                    >
                      {result.severity.level}
                      {result.severity.percentage > 0 &&
                        ` (${result.severity.percentage}%)`}
                    </span>
                  </div>
                </div>

                {/* Growth Stage Card */}
                <div className="bg-gradient-to-r from-purple-500 to-pink-600 rounded-2xl shadow-xl p-6 text-white animate-fadeIn">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <Clock className="w-8 h-8" />
                      <div>
                        <h4 className="font-semibold text-purple-100">
                          Growth Stage
                        </h4>
                        <p className="text-2xl font-bold">
                          {result.growth_stage.stage}
                        </p>
                      </div>
                    </div>
                    <div className="bg-white/20 px-4 py-2 rounded-full">
                      <span className="text-sm font-semibold">
                        Stage {result.growth_stage.code}
                      </span>
                    </div>
                  </div>
                </div>

                {/* Comprehensive Treatment Plan */}
                {result.treatment_plan && (
                  <div className="bg-white rounded-2xl shadow-2xl overflow-hidden border-t-4 border-gradient-to-r from-blue-500 to-purple-600 animate-fadeIn">
                    {/* Header */}
                    <div className="bg-gradient-to-r from-blue-500 via-purple-600 to-pink-600 p-6">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3">
                          <div className="bg-white p-3 rounded-xl shadow-lg">
                            <Sparkles className="w-8 h-8 text-purple-600" />
                          </div>
                          <div className="text-white">
                            <h3 className="text-3xl font-bold">
                              Complete Treatment Plan
                            </h3>
                            <p className="text-blue-100 mt-1 flex items-center gap-2">
                              <span className="bg-white/20 px-3 py-1 rounded-full text-sm font-semibold">
                                🤖 AI-Powered by Groq LLM
                              </span>
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>

                    {/* Treatment Content */}
                    <div className="p-8">
                      <div className="prose prose-lg max-w-none">
                        <div className="bg-gradient-to-br from-blue-50 via-purple-50 to-pink-50 rounded-2xl p-8 whitespace-pre-wrap text-gray-800 leading-relaxed border-2 border-purple-200 shadow-inner">
                          <div className="font-medium text-base">
                            {result.treatment_plan}
                          </div>
                        </div>
                      </div>

                      {/* Action Buttons */}
                      <div className="mt-6 grid grid-cols-1 sm:grid-cols-2 gap-4">
                        <button
                          onClick={handleDownloadTreatment}
                          className="bg-gradient-to-r from-green-500 to-green-600 hover:from-green-600 hover:to-green-700 text-white font-bold py-4 rounded-xl transition-all flex items-center justify-center gap-2 shadow-lg hover:shadow-xl transform hover:-translate-y-0.5"
                        >
                          <Download className="w-5 h-5" />
                          Download Treatment Plan
                        </button>

                        <button
                          onClick={handleShareTreatment}
                          className="bg-gradient-to-r from-blue-500 to-blue-600 hover:from-blue-600 hover:to-blue-700 text-white font-bold py-4 rounded-xl transition-all flex items-center justify-center gap-2 shadow-lg hover:shadow-xl transform hover:-translate-y-0.5"
                        >
                          <Share2 className="w-5 h-5" />
                          Share Treatment
                        </button>
                      </div>

                      {/* Footer Note */}
                      <div className="mt-6 bg-yellow-50 border-l-4 border-yellow-500 p-4 rounded-lg">
                        <p className="text-sm text-yellow-800">
                          <span className="font-bold">⚠️ Important:</span> This
                          AI-generated treatment plan is for guidance only. For
                          severe cases or if symptoms persist, please consult a
                          local agricultural expert or extension officer.
                        </p>
                      </div>
                    </div>
                  </div>
                )}
              </>
            )}

            {/* Initial State */}
            {!result && !error && !detecting && (
              <div className="bg-white rounded-2xl shadow-lg p-16 text-center">
                <div className="bg-gradient-to-br from-green-100 to-blue-100 w-24 h-24 rounded-full flex items-center justify-center mx-auto mb-6 shadow-lg">
                  <Leaf className="w-12 h-12 text-green-600" />
                </div>
                <h3 className="text-2xl font-bold text-gray-700 mb-3">
                  Ready to Analyze
                </h3>
                <p className="text-gray-600 max-w-md mx-auto">
                  Upload a clear image of your crop leaf to get instant
                  AI-powered disease diagnosis and comprehensive treatment
                  recommendations.
                </p>
                <div className="mt-6 flex items-center justify-center gap-4 text-sm text-gray-500">
                  <div className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-green-500" />
                    Fast Detection
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-green-500" />
                    AI Treatment Plans
                  </div>
                  <div className="flex items-center gap-2">
                    <CheckCircle2 className="w-4 h-4 text-green-500" />
                    Expert Advice
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Custom CSS for animations */}
      <style jsx>{`
        @keyframes fadeIn {
          from {
            opacity: 0;
            transform: translateY(10px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }

        @keyframes shake {
          0%,
          100% {
            transform: translateX(0);
          }
          25% {
            transform: translateX(-5px);
          }
          75% {
            transform: translateX(5px);
          }
        }

        .animate-fadeIn {
          animation: fadeIn 0.5s ease-out;
        }

        .animate-shake {
          animation: shake 0.5s ease-out;
        }
      `}</style>
    </div>
  );
};

export default DiseaseDetection;
